// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

public class Q4{
    public static void main(String[] args){
        int number1 = 0;
        int number2 = 1;
        int placeHolder = number1 + number2;
        int result = 0;

        while (placeHolder < 4000000){
            if (placeHolder % 2 == 0){
                result += placeHolder;
            }
            int temp = number2;
            number2 = placeHolder;
            number1 = temp;
            placeHolder = number1 + number2;
        }
        System.out.print(result);
    }
}